#!/bin/bash
# $BACKUP_DIR can be changed at: $HOME/.config/pads/profile.cfg

printf " :: Backing up system to ${BACKUP_DIR}...\n"
sudo rsync --delete -aAXH "${HOME}/pads" "${BACKUP_DIR}/pads/pads_v$(pads -v)"
sudo tar -cf "${BACKUP_DIR}/pads/pads_v$(pads -v).tar.gz" "${BACKUP_DIR}/pads/pads_v$(pads -v)"
sudo rsync --delete -aAXH --exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/home/*","/media/*","/lost+found"} / "${BACKUP_DIR}/arch"
[[ $? -eq 0 ]] && printf "Done!\n"
