#!/bin/bash

# This resets $PATH to default
logMsg "resetpath..${LINENO}: Resetting \$PATH..."
printf "${PATH}\n"
export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
printf "${PATH}\n"

